# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdata
    username: root
    password: abc123##
    driver-class-name: com.mysql.jdbc.Driver
    # Redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 300
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

# MyBatis配置
mybatis:
  type-aliases-package: com.boot.dao
  mapper-locations: mappers/PersonMapper.xml