# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-mybatis-test
    username: root
    password: abc123##
    driver-class-name: com.mysql.jdbc.Driver
# MyBatis配置
mybatis:
  type-aliases-package: com.boot.dao
  mapper-locations: mappers/*Mapper.xml
server:
  port: 8080